# Generated by Django 2.1.2 on 2018-10-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0006_auto_20181004_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistoriaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='image/')),
                ('observacao', models.TextField(blank=True, default='NENHUMA OBSERVAÇÃO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.EmpresaModel')),
            ],
        ),
    ]
