# Generated by Django 2.1.2 on 2018-10-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoriamodel',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
