# Generated by Django 2.1.2 on 2018-11-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistorias', '0003_auto_20181018_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistoriamodel',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagem/'),
        ),
    ]
