# Generated by Django 2.0.6 on 2018-07-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_cad', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('quadra', models.CharField(max_length=10)),
                ('lote', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('responsavel', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
