# Generated by Django 2.0.6 on 2018-09-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='ref_cad',
            field=models.CharField(max_length=20),
        ),
    ]
