# Generated by Django 2.0.6 on 2018-09-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20180911_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='categoria_atividade',
            field=models.CharField(choices=[('prestacao', 'PRESTAÇÃO DE SERVIÇOS'), ('comercio', 'COMÉRCIO'), ('industria', 'INDÚSTRIA')], default='prestacao', max_length=6),
        ),
    ]
