# Generated by Django 2.0.6 on 2018-09-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresamodel_categoria_atividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='categoria_atividade',
            field=models.CharField(choices=[('prestacao', 'PRESTAÇÃO DE SERVIÇOS'), ('comercio', 'COMÉRCIO'), ('industria', 'INDÚSTRIA')], default='prestacao', max_length=10),
        ),
    ]
