# Generated by Django 2.0.6 on 2018-10-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_auto_20181001_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodel',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=20),
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='categoria_distrito',
            field=models.CharField(choices=[('1', 'DISTRITO I'), ('2', 'DISTRITO II'), ('3', 'DISTRITO III'), ('4', 'DISTRITO IV'), ('5', 'DISTRITO V'), ('5', 'DISTRITO VI'), ('0', 'OUTROS')], default='0', max_length=2),
        ),
    ]
