# Generated by Django 2.1.2 on 2018-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_auto_20181004_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresamodel',
            name='situacao',
        ),
        migrations.AlterField(
            model_name='empresamodel',
            name='atividade',
            field=models.CharField(default='NÃO DEFINIDA', max_length=200),
        ),
    ]
